hlxsites/caesars

- caesars-palace/blocks/columns/columns.css
- caesars-palace/blocks/columns/columns.js
- caesars-palace/styles/styles.css
Fix #18
- Before: https://main--caesars--hlxsites.hlx.page/caesars-palace/drafts/arumsey/column-variations
- After: https://issue-18-section--caesars--hlxsites.hlx.page/caesars-palace/drafts/arumsey/column-variations
- added support for full width cet cards
> Section Variations #18

- caesars-palace/blocks/faq/faq.css
- caesars-palace/blocks/faq/faq.js
Fix #45 
Before: https://main--caesars--hlxsites.hlx.page/caesars-palace/drafts/jfait/faq
After: https://issue-45-faq-block--caesars--hlxsites.hlx.page/caesars-palace/drafts/jfait/faq
Live Example:  https://www.caesars.com/caesars-palace/things-to-do/garden-of-the-gods-pool-oasis#894cd7a7-8e63-3d2f-9c22-236cb2dcda8e
FAQ block with css and js (decoration and interactivity to expand and collapse)
> Issue45 FAQ Block : Accordian like faq block

- caesars-palace/blocks/carousel/carousel.js
Fix https://github.com/hlxsites/caesars/issues/59
- After: https://issue-11-carousel-variations--caesars--hlxsites.hlx.page/caesars-palace/drafts/tmathern/carousel
> Bugfix: Carousel

- caesars-palace/blocks/carousel/carousel.css
- caesars-palace/blocks/carousel/carousel.js
- caesars-palace/styles/styles.css
Fix https://github.com/hlxsites/caesars/issues/60
- Before: https://main--caesars--hlxsites.hlx.page/caesars-palace/homepage
- After: https://issue-60-carousel-with-video--caesars--hlxsites.hlx.page/caesars-palace/drafts/tmathern/homepage
Support having a mix of images and videos in carousel.
> Block: Allow carousels to contain videos and/or images

- caesars-palace/blocks/carousel/carousel.css
- caesars-palace/blocks/stats/stats.js
- caesars-palace/styles/styles.css
Fix multiple small CSS issues.
- After: https://casino-css-fixes--caesars--hlxsites.hlx.page/caesars-palace/drafts/tmathern/casino
Additional CSS changes to support styling the casino page:
- adds classes/metadata for text(title and content) alignment and color
- fixes stats to be centered no matter how many columns there are
> Additional CSS changes to support styling the casino page

- caesars-palace/blocks/columns/columns.css
- caesars-palace/styles/styles.css
Fix #35 
- After: https://css-fixes-things-to-do--caesars--hlxsites.hlx.page/caesars-palace/drafts/swbarman/things-to-do
> Add css fixes for <p> alignment on the things-to-do page

- caesars-palace/blocks/card-list/card-list.css
- caesars-palace/scripts/scripts.js
- Before: https://main--caesars--hlxsites.hlx.page/caesars-palace/things-to-do/nightlife
- After: https://issue-12-minor-fixes--caesars--hlxsites.hlx.page/caesars-palace/things-to-do/nightlife
- update scripts to locate json files correctly
- set z-index on card count appropriately
> Card List: Minor bug fixes

- caesars-palace/blocks/carousel/carousel.css
- caesars-palace/blocks/carousel/carousel.js
- caesars-palace/blocks/featured-card/featured-card.css
- caesars-palace/blocks/featured-card/featured-card.js
- caesars-palace/blocks/tabs/tabs.css
- caesars-palace/blocks/tabs/tabs.js
- caesars-palace/blocks/video-with-alt-image/video-with-alt-image.css
Fix: Improve Lighthouse scores
- After: https://optimize--caesars--hlxsites.hlx.page/caesars-palace/drafts/tmathern/featured-card
A set of improvements to improve overall lighthouse scores
> Featured-card bugfix (no-background support)

- caesars-palace/blocks/carousel/carousel.js
Fix #<gh-issue-id>
- After: https://video-carousel-optimized--caesars--hlxsites.hlx.page/caesars-palace/
> Video carousel optimized

- caesars-palace/blocks/accordion/accordion.css
- caesars-palace/blocks/featured-card/featured-card.css
- caesars-palace/blocks/tabs/tabs.css
- caesars-palace/styles/styles.css
Fix edge cases in blocks CSS
- After: https://css-fixes--caesars--hlxsites.hlx.page/caesars-palace/things-to-do/weddings
Set of CSS fixes to handle some edge cases in blocks
> Set of CSS fixes to handle some edge cases in blocks

- caesars-palace/blocks/card-list/card-list.css
- caesars-palace/blocks/card-list/card-list.js
- Before: https://main--caesars--hlxsites.hlx.page/caesars-palace/restaurants
- After: https://issue-12-minor-fixes-2--caesars--hlxsites.hlx.page/caesars-palace/restaurants
- Fixed the scrolling issue when paging & filtering.
> Card List:  Scrolling Issue Fix

- caesars-palace/blocks/accordion/accordion.css
- caesars-palace/blocks/carousel/carousel.js
- caesars-palace/blocks/columns/columns.js
- caesars-palace/scripts/scripts.js
Fix background image handling.
- After: https://optimize-more--caesars--hlxsites.hlx.page/caesars-palace/
- Optimize background image handling.
> Optimize background image handling

- caesars-palace/blocks/card-list/card-list.js
- Before: https://main--caesars--hlxsites.hlx.page/caesars-palace/restaurants
- After: https://issue-12-clean-up--caesars--hlxsites.hlx.page/caesars-palace/restaurants
- Sort filter option alphabetically
- Clean up javascript and add comments.
> Card List:  Sort Filter Options & JS Clean Up

- caesars-palace/blocks/footer/footer.css
- caesars-palace/blocks/slider/slider.css
- caesars-palace/scripts/scripts.js
Fix #71
- After: https://issue-71-footerStyling--caesars--hlxsites.hlx.page/caesars-palace/
- add rewards slider to footer
- a bit more css clean up
> Block: Rewards footer #71

- caesars-palace/blocks/library-config/library-config.css
- caesars-palace/blocks/library-config/library-config.js
- caesars-palace/blocks/library-config/library-utils.js
- caesars-palace/blocks/library-config/lists/assets.js
- caesars-palace/blocks/library-config/lists/blocks.js
- caesars-palace/blocks/library-config/lists/placeholders.js
- caesars-palace/scripts/scripts.js
- tools/sidekick/config.json
Fix #117 
Adding block library functionality
> Adding block library functionality

- caesars-palace/blocks/carousel/carousel.css
- caesars-palace/blocks/carousel/carousel.js
- caesars-palace/scripts/scripts.js
Fix https://github.com/hlxsites/caesars/issues/106
- Before (old design): https://main--caesars--hlxsites.hlx.page/caesars-palace/drafts/tmathern/carousel
- After (new *additional* design as variant): https://issue-106-showcase-carousel--caesars--hlxsites.hlx.page/caesars-palace/drafts/tmathern/carousel-cards
- Variation for carousels product showcase (as seen in https://www.caesars.com/caesars-palace/hotel for rooms)
> Block: Carousel variant: Product showcase

- caesars-palace/blocks/columns/columns.css
- caesars-palace/blocks/faq/faq.css
- caesars-palace/blocks/hero/hero.css
- caesars-palace/blocks/highlight-card/highlight-card.css
- caesars-palace/blocks/slider/slider.css
- caesars-palace/blocks/slider/slider.js
Fix dynamic ellipsis in slider cards
- After: https://authoring-slider-cards--caesars--hlxsites.hlx.page/caesars-palace/drafts/tmathern/card-slider
- Dynamic ellipsis in slider cards
- Increase size card for extended text so more text fits and doesn't get cut off
- Changes authoring experience to author only the text, short text is done dynamically
> Dynamic ellipsis in slider cards

- caesars-palace/blocks/carousel/carousel.js
Fix performance.
- After: https://reoptimize--caesars--hlxsites.hlx.page/caesars-palace/
- Continue to look for Lighthouse score optimizations
- Make a bunch of event listeners passive to improve scrolling performance
> Continue to look for Lighthouse score optimizations

- caesars-palace/styles/styles.css
Fix #141 
- Before: https://main--caesars--hlxsites.hlx.page/caesars-palace/caesars-palace/drafts/swbarman/hero-align-right
- After: https://issue-141-hero-title--caesars--hlxsites.hlx.page/caesars-palace/drafts/swbarman/hero-align-right
> Hero title: Add right aligned styling

- caesars-palace/blocks/product-details/product-details.css
- caesars-palace/blocks/product-details/product-details.js
Fix #114 
- Before: https://main--caesars--hlxsites.hlx.page/caesars-palace/drafts/amol/hells-kitchen
- After: https://issue-117-product-details--caesars--hlxsites.hlx.page/caesars-palace/drafts/amol/hells-kitchen
Pulling from the new Excel to get json. Automatically creating sections based on the product details page and creating content structure to pass to already existing blocks and rendering them on the page. The page only has one block in it pointing to the product json endpoint
I have created three separate issues to build some other blocks at the top of the page that will be needed for product details. once those blocks are built, I will just have to pass the content from json and call those blocks in this code.
Please ignore the branch name it should be 114 to match the issue but …
> Product Details using json content

- caesars-palace/blocks/library-config/library-config.js
- caesars-palace/blocks/library-config/library-utils.js
- caesars-palace/blocks/library-config/lists/assets.js
- caesars-palace/blocks/library-config/lists/blocks.js
- caesars-palace/blocks/library-config/lists/buttons.js
- caesars-palace/blocks/library-config/lists/placeholders.js
- caesars-palace/blocks/library-config/lists/sections.js
- caesars-palace/blocks/library-config/lists/templates.js
Fix #144 
- Before: https://main--caesars--hlxsites.hlx.page/caesars-palace/block-library/library
- After: https://issue-144-block-library--caesars--hlxsites.hlx.page/caesars-palace/block-library/library
Adding blocks, sections, templates, buttons to the block library for easy authoring
> Adding blocks, buttons, sections and templates

- caesars-palace/blocks/featured-card/featured-card.css
- caesars-palace/blocks/slider/slider.css
Fix #136 
- After: https://issue-136-casino-page--caesars--hlxsites.hlx.page/caesars-palace/drafts/swbarman/casino
> Issue 136: Casino Page

- caesars-palace/blocks/menu-options/menu-options.css
- caesars-palace/blocks/product-details/product-details.js
- caesars-palace/scripts/scripts.js
Fix #164 
- Before: https://main--caesars--hlxsites.hlx.page/caesars-palace/drafts/amol/hells-kitchen
- After: https://issue-164-product-details--caesars--hlxsites.hlx.page/caesars-palace/drafts/amol/hells-kitchen
Added menu options and product quick facts bands to the details page
> Issue 164 product details

- caesars-palace/blocks/faq/faq.css
Fix https://github.com/hlxsites/caesars/issues/198
- Before: https://main--caesars--hlxsites.hlx.page/caesars-palace/things-to-do/garden-of-the-gods-pool-oasis
- After: https://issue-198--caesars--hlxsites.hlx.page/caesars-palace/things-to-do/garden-of-the-gods-pool-oasis
- Issue 198: Fix link styling in FAQ
> Issue 198: Fix link styling in FAQ

- caesars-palace/blocks/slider/slider.css
Fix #178 
- Before: https://main--caesars--hlxsites.hlx.page/caesars-palace/hotel
- After: https://issue-178-slider-fix-mobile-tablet-view--caesars--hlxsites.hlx.page/caesars-palace/hotel
> Issue 178: slider fix mobile tablet view

- caesars-palace/blocks/slider/slider.css
- caesars-palace/blocks/slider/slider.js
- caesars-palace/scripts/scripts.js
Fix https://github.com/hlxsites/caesars/issues/197
- Before: https://main--caesars--hlxsites.hlx.page/caesars-palace/drafts/tmathern/issue-197
- After: https://issue-197-v2--caesars--hlxsites.hlx.page/caesars-palace/drafts/tmathern/issue-197
- Use a resizeObserver to handle auto-ellipsis.
- Also fixes a typo to fix padding on mobile.
> Issue 197: Slider confused if appearing multiple times in a section (+ refactoring)

- caesars-palace/blocks/columns/columns.css
Fix N/A (found during another review)
- Before: https://main--caesars--hlxsites.hlx.page/caesars-palace/hotel
- Before: https://main--caesars--hlxsites.hlx.page/caesars-palace/things-to-do
- After: https://fix-zig-zag--caesars--hlxsites.hlx.page/caesars-palace/hotel
- After: https://fix-zig-zag--caesars--hlxsites.hlx.page/caesars-palace/things-to-do
Remove zig-zag, using cet-card is enough.
> Update zig-zag CSS

- caesars-palace/blocks/slider/slider.css
Fix #<gh-issue-id>
- After: https://issue-178-slider-fix-mobile-tablet-view--caesars--hlxsites.hlx.page/caesars-palace/casino
Fix a side-effect on the rewards footer button
> Issue 178 : Rewards button side effect

- caesars-palace/blocks/highlight-card/highlight-card.css
Fix N/A
- Before: https://main--caesars--hlxsites.hlx.page/caesars-palace/things-to-do/football
- After: https://card-scaling-issue--caesars--hlxsites.hlx.page/caesars-palace/things-to-do/football
- Scale highlight card so it right-aligns with other items.
> Scale highlight card to right-align with other elements

- caesars-palace/blocks/columns/columns.js
Fix https://github.com/hlxsites/caesars/issues/196
- Before: https://main--caesars--hlxsites.hlx.page/caesars-palace/drafts/tmathern/issue-196
- After: https://issue-196--caesars--hlxsites.hlx.page/caesars-palace/drafts/tmathern/issue-196
Repro: The issue can be reproduced by changing window size with the pointer. On size change switch mobile/desktop, images will be added to the DOM/
> Issue 196: Fix multiple additions of images to DOM

- caesars-palace/blocks/slider/slider.css
Fix #<gh-issue-id>
- After: https://refactor-buttons--caesars--hlxsites.hlx.page/caesars-palace/drafts/swbarman/casino
> Refactor buttons

- caesars-palace/blocks/quick-facts-hours/quick-facts-hours.css
- caesars-palace/blocks/quick-facts-hours/quick-facts-hours.js
Fix #219 
- Before: https://main--caesars--hlxsites.hlx.page/caesars-palace/drafts/tmathern/quick-facts-hours
- After: https://issue-219-make-entire-quick-facts-clickable--caesars--hlxsites.hlx.page/caesars-palace/drafts/tmathern/quick-facts-hours
> [Issue-219]: Make quick facts hours container clickable

- caesars-palace/blocks/product-details/product-details.js
- caesars-palace/scripts/scripts.js
Fix #194 
- Before: https://main--caesars--hlxsites.hlx.page/caesars-palace/restaurants/mr-chow
- After: https://issue-194-hours-fix--caesars--hlxsites.hlx.page/caesars-palace/restaurants/mr-chow
Support non date entries in open/close time from excel.
> Issue 194: Support non date entries for open and close time

- caesars-palace/blocks/product-details/product-details.js
- caesars-palace/styles/styles.css
Fix https://github.com/hlxsites/caesars/issues/185
- Before: https://main--caesars--hlxsites.hlx.page/caesars-palace/drafts/tmathern/bacchanal-buffet
- After: https://issue-185--caesars--hlxsites.hlx.page/caesars-palace/drafts/tmathern/bacchanal-buffet
- Adds stats to product pages (with icons support for stats value)
> Issue 185: Add stats to product Excel/product pages

- caesars-palace/blocks/carousel/carousel.js
- caesars-palace/blocks/featured-card/featured-card.css
- caesars-palace/styles/styles.css
Fix https://github.com/hlxsites/caesars/issues/234, https://github.com/hlxsites/caesars/issues/235
- After: https://small-fixes-april-2023--caesars--hlxsites.hlx.page/caesars-palace/casino
- Before: https://main--caesars--hlxsites.hlx.page/caesars-palace/hotel
- After: https://small-fixes-april-2023--caesars--hlxsites.hlx.page/caesars-palace/hotel
- Fix mobile display of image in feature card
- Fix background colors in some cases for feature card
- Set timeout so carousel can grab proper styling from page to display with correct alignment
- Hero images got a gradient applied (not applied yet on video or carousel hero sections)
> Some CSS fixes for casino and hotel pages

- caesars-palace/blocks/slider/slider.css
Fix #233 
- After: https://issue-233--caesars--hlxsites.hlx.page/caesars-palace/casino
> [Issue - 233] : Fix slider image issue
